apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: codegen-gl-456 
  description: Secure Supply Chain Example for Code Generation Application example that generate code in countless programming languages.   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:
    # ArgoCD apps from this template used rhtap-gitops as the grouping
    argocd/app-selector: rhtap/gitops=codegen-gl-456  
    janus-idp.io/tekton: codegen-gl-456 
    backstage.io/kubernetes-id: codegen-gl-456 
    backstage.io/techdocs-ref: dir:. 
    quay.io/repository-slug: yangcao/codegen-gl-456
  tags: ["ai", "llamacpp", "vllm", "python"] 
spec:
  type: service
  owner: user:guest 
  lifecycle: experimental
 